[package]
name = "realman"
version = "0.1.0"
edition = "2021"
authors = ["Leon <echo_ai@foxmail.com>"]
description = "realman robot Rust sdk"
license = "MIT"
repository = "https://github.com/EchoRust/realman"
keywords = ["realman", "robot"]

[dependencies]
